name: Release Juicy Noise Android application

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'


env:
  ANDROID_SDK_PATH: 'android-sdk'
  ANDROID_SDK_VERSION: 34

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install APT dependencies
      run: |
        sudo apt-get install \
          -y \
          --no-install-recommends \
          wget \
          unzip

    - name: Restore Android SDK cache
      id: cache-android-sdk
      uses: actions/cache@v3
      with:
        path: ${{ env.ANDROID_SDK_PATH }}
        key: android-sdk

    - name: Install Android SDK
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        archive_name="tools.zip"

        wget \
          -q \
          https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip \
          -O "${archive_name}"

          sdk_path="${{ env.ANDROID_SDK_PATH }}"
          mkdir -p "${sdk_path}"

        unzip \
          "${archive_name}" \
          -d "${sdk_path}"

        mv "${sdk_path}/cmdline-tools" "${sdk_path}/latest"
        mkdir "${sdk_path}/cmdline-tools"
        mv "${sdk_path}/latest" "${sdk_path}/cmdline-tools/latest"

        sdk_manager="${sdk_path}/cmdline-tools/latest/bin/sdkmanager"

        chmod +x "${sdk_manager}"

        echo "y" | "${sdk_manager}" --licenses
        echo "y" | "${sdk_manager}" "platforms;android-${{ env.ANDROID_SDK_VERSION }}"
        echo "y" | "${sdk_manager}" "build-tools;${{ env.ANDROID_SDK_VERSION }}.0.0"
        echo "y" | "${sdk_manager}" "platform-tools"

    - name: Set Android SDK to PATH
      shell: bash
      run: |
        export ANDROID_HOME="${{ env.ANDROID_SDK_PATH }}"

    - name: Build Android client
      run: |
        rev=${{ startsWith(github.ref, 'refs/tags/') &&  github.ref_name || github.sha }}

        pushd "juicy-noise-android"

        ./gradlew assembleDebug

        popd

        mv \
          "juicy-noise-android/app/build/outputs/apk/debug/app-debug.apk" \
          "juicy-noise-${rev}.apk"

    - name: Upload artifacts for Android
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: '*.apk'
        if-no-files-found: error
        retention-days: 1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: '${{ secrets._GITHUB_PAT }}'
        files: '*.apk'
