name: Release Juicy Noise Android application

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install APT dependencies
      run: |
        sudo apt-get install \
          -y \
          --no-install-recommends \
          wget \
          unzip

    - name: Install Android SDK
      run: |
        archive_name="tools.zip"

        wget \
          -q \
          https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip \
          -O "${archive_name}"

        android_lib="/usr/local/lib/android"
        mkdir -p "${android_lib}"
        sdk_path="${android_lib}/sdk"

        unzip \
          "${archive_name}" \
          -d "${sdk_path}"

        mv "${sdk_path}/cmdline-tools" "${sdk_path}/latest"
        mkdir "${sdk_path}/cmdline-tools"
        mv "${sdk_path}/latest" "${sdk_path}/cmdline-tools/latest"

        sdk_manager="${sdk_path}/cmdline-tools/latest/bin/sdkmanager"

        chmod +x "${sdk_manager}"

        echo "y" | "${sdk_manager}" --licenses
        echo "y" | "${sdk_manager}" "platforms;android-34"
        echo "y" | "${sdk_manager}" "build-tools;34.0.0"
        echo "y" | "${sdk_manager}" "platform-tools"

        export ANDROID_HOME="${sdk_path}"

    - name: Build Android client
      run: |
        rev=${{ startsWith(github.ref, 'refs/tags/') &&  github.ref_name || github.sha }}

        pushd "juicy-noise-android"

        ./gradlew assembleDebug

        popd

        mv \
          "juicy-noise-android/app/build/outputs/apk/debug/app-debug.apk" \
          "juicy-noise-${rev}.apk"

    - name: Upload artifacts for Android
      if: startsWith(github.ref, 'refs/tags/') == 'false'
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: '*.apk'
        if-no-files-found: error
        retention-days: 1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: '${{ secrets._GITHUB_PAT }}'
        files: '*.apk'
